### PR TITLE
tests for PAN validation

### PR DESCRIPTION
**Pull request by vimalsuresh**
## What does this pull request do?

tests for PAN validation

## Why make these changes?

As part of tech debt ticket, changes were made to PAN validation, This PR is to test the PAN  validation

## Checklist

https://dsdmoj.atlassian.net/browse/TA-2294

### CODE REVIEW

**Review by solomonahmed — DISMISSED** [review]
Good coverage of PAN validation.

Only thought was whether it was worth splitting out the bulkload/manual tests into separate files?  Or tagging them to indicate manual or bulkload as has been done in other feature test files?

**Comment by vimalsuresh** [comment]
> Good coverage of PAN validation.
> 
> Only thought was whether it was worth splitting out the bulkload/manual tests into separate files? Or tagging them to indicate manual or bulkload as has been done in other feature test files?

**Comment by vimalsuresh** [comment]
> Good coverage of PAN validation.
> 
> Only thought was whether it was worth splitting out the bulkload/manual tests into separate files? Or tagging them to indicate manual or bulkload as has been done in other feature test files?

The manual tests are tagged using @manual_submission tag.

**Comment by solomonahmed** [comment]
> > Good coverage of PAN validation.
> > Only thought was whether it was worth splitting out the bulkload/manual tests into separate files? Or tagging them to indicate manual or bulkload as has been done in other feature test files?
> 
> The manual tests are tagged using @manual_submission tag.

Cool. Np then.  All looks good.

**Review by solomonahmed — APPROVED** [review]

**Pull request merged**
