### PR TITLE
TA-900/1 Sending Hearing Fee feature tests

### PR DESCRIPTION
**Pull request by atrichowdhury**
## What does this pull request do?

Feature tests for Sending Hearing Fee Changes

## Why make these changes?

Legislative Changes

## Checklist

- [ ] Provided link to a JIRA ticket: https://dsdmoj.atlassian.net/browse/TA-900
https://dsdmoj.atlassian.net/browse/TA-901

### CODE REVIEW

**Review by solomonahmed — APPROVED** [review]
LGTM. I did wonder whether it might be worth adding some notes at the beginning of the tests to explain the use of the XXLSC_TEST_SUBMISSION_PERIOD profile option.  Then again once the system date is after 19th Oct (essentially just over 3 weeks away) the tests will naturally pass without the profile option change so perhaps it is fine.

**Comment by DeepakTanna** [comment]
Maybe we should reset XXLSC_TEST_SUBMISSION_PERIOD to its original value in DEV and TST.

**Comment by solomonahmed** [comment]
> Maybe we should reset XXLSC_TEST_SUBMISSION_PERIOD to its original value in DEV and TST.

I think Glen has raised a ticket to get the profile option reset on DEV/TST/UAT once we deploy the changes to PROD.

**Comment by your** [comment]
> LGTM. I did wonder whether it might be worth adding some notes at the beginning of the tests to explain the use of the XXLSC_TEST_SUBMISSION_PERIOD profile option. Then again once the system date is after 19th Oct (essentially just over 3 weeks away) the tests will naturally pass without the profile option change so perhaps it is fine.

I'd agree with @solomonahmed, as for someone looking at the feature for the first time it wouldn't be necessarily clear what's the profile option for. The scenario description kind of gives some clues though. It might be worth documenting in the README at some point this if we keep on relying on this for this kind of tests.

**Review by your — APPROVED** [review]

**Review by your — COMMENTED** [review]
We probably need to wait to try these on UAT before merging, as we updated the test submission data.

**Pull request merged**
