### PR TITLE
move asylum pricing tests to verbose format

### PR DESCRIPTION
**Pull request by vimalsuresh**
## What does this pull request do?
Moved Asylum pricing tests to more verbose format

## Why make these changes?

We had discussions in the team and wanted to refactor the tests to make them more readable and easy to use. Most of the logic for pricing was hidden in ruby code which the team did not understand. So moved the logic to the feature level.

## Checklist
Ticket: https://dsdmoj.atlassian.net/browse/TA-2191

### CODE REVIEW

**Review by GlenHarper — CHANGES_REQUESTED** [review]
The Escape Fee calculation is incorrectly deducting additional fees.
Any additional fees should be excluded from the calculation.
The Escape Fee should apply when Profit_Cost + Counsel_Cost > escape threshold.

**Review by GlenHarper — APPROVED** [review]
Having received clarification from the business it seems that the additional_payments element is being handled correctly when triggering the Escape Fee flag.
Good work Vimal.

**Review by jamidodger — APPROVED** [review]
Good work Vimal.

**Review by GlenHarper — APPROVED** [review]
Well done.

**Pull request merged**
